{"name": "test_01", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_assume.py:31: AssumptionFailure\n>>\tpytest.assume(0 == 1)\nAssertionError: assert False\n\ntest_assume.py:33: AssumptionFailure\n>>\tpytest.assume(1 == 2)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_assume.py:31: AssumptionFailure\nE               >>\tpytest.assume(0 == 1)\nE               AssertionError: assert False\nE               \nE               test_assume.py:33: AssumptionFailure\nE               >>\tpytest.assume(1 == 2)\nE               AssertionError: assert False\n\n../../xunivenvs/hogwarts/lib/python3.6/site-packages/six.py:702: FailedAssumption"}, "description": "用例1", "start": 1622455640541, "stop": 1622455640538, "uuid": "0c7b92bf-83d8-4269-92c9-c33cfa77c39c", "historyId": "cbdda80ee71ab2ed17a95f8118b95d4b", "testCaseId": "e8de285ece3f8c9f185d004b607de2fe", "fullName": "test_assume.Test#test_01", "labels": [{"name": "suite", "value": "test_assume"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "warronMacBook-Pro.local"}, {"name": "thread", "value": "47643-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_assume"}]}