{"name": "test_02", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n1 Failed Assumptions:\n\ntest_assume_8_2.py:38: AssumptionFailure\n>>\tpytest.assume(3 == 5)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               1 Failed Assumptions:\nE               \nE               test_assume_8_2.py:38: AssumptionFailure\nE               >>\tpytest.assume(3 == 5)\nE               AssertionError: assert False\n\n../../xunivenvs/hogwarts/lib/python3.6/site-packages/six.py:702: FailedAssumption"}, "description": "用例2", "start": 1622772836604, "stop": 1622772836603, "uuid": "9bf5a7c0-dedb-4e4c-8793-370f9dc28adc", "historyId": "33ea40d5765b9da3dc87915c080f765d", "testCaseId": "db8b6ec8e52a89bf1c472534c1df205c", "fullName": "test_assume_8_2.Test#test_02", "labels": [{"name": "suite", "value": "test_assume_8_2"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "warronMacBook-Pro.local"}, {"name": "thread", "value": "54587-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_assume_8_2"}]}