{"name": "test_add_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 201 == 300", "trace": "self = <test_calculator_3_2_practice.TestCalc object at 0x11049c7f0>\n\n    def test_add_1(self):\n        datas = [\n        (1,1,2),\n        (100,200,201),\n        (1,0,1),\n    ]\n        for data in datas:\n>           assert data[2] == self.calc.add(data[0], data[1])\nE           assert 201 == 300\n\ntest_calculator_3_2_practice.py:68: AssertionError"}, "start": 1623030792961, "stop": 1623030792962, "uuid": "5d7fed5c-019a-4786-84c0-4ad2938e9270", "historyId": "8c0b332dcf8fd406992a4a976d9d742c", "testCaseId": "ad6e4cf384aab9db46398e9215800cbc", "fullName": "test_calculator_3_2_practice.TestCalc#test_add_1", "labels": [{"name": "suite", "value": "test_calculator_3_2_practice"}, {"name": "subSuite", "value": "TestCalc"}, {"name": "host", "value": "warronMacBook-Pro.local"}, {"name": "thread", "value": "6126-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calculator_3_2_practice"}]}