{"name": "test_assume", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_assume.py:20: AssumptionFailure\n>>\tpytest.assume(1 == 2)\nAssertionError: assert False\n\ntest_assume.py:21: AssumptionFailure\n>>\tpytest.assume(2 == 3)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_assume.py:20: AssumptionFailure\nE               >>\tpytest.assume(1 == 2)\nE               AssertionError: assert False\nE               \nE               test_assume.py:21: AssumptionFailure\nE               >>\tpytest.assume(2 == 3)\nE               AssertionError: assert False\n\ne:\\virtualtest\\warron\\lib\\site-packages\\six.py:702: FailedAssumption"}, "start": 1612423398532, "stop": 1612423398531, "uuid": "fa89752a-a696-4a3e-98e3-2e371edc0c4f", "historyId": "c0c0e00a2dc8eb0c23efb3aaafbb3473", "testCaseId": "1fc213c51f170fbf8bc4aaf6544f8118", "fullName": "test_assume#test_assume", "labels": [{"name": "suite", "value": "test_assume"}, {"name": "host", "value": "wangwei"}, {"name": "thread", "value": "3216-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_assume"}]}