{"name": "test_a", "status": "skipped", "statusDetails": {"message": "XFAIL deliberate fail\n\nAssertionError: assert False", "trace": "@pytest.mark.dependency()\n    @pytest.mark.xfail(reason=\"deliberate fail\")\n    def test_a():\n        # 失败的case\n>       assert False\nE       assert False\n\ntest_dependency_8_4.py:17: AssertionError"}, "start": 1622773744377, "stop": 1622773744377, "uuid": "ff176d64-222d-4387-b44a-5c0c5c1b8305", "historyId": "127f77aa29dee7235840c5ff24f770bc", "testCaseId": "85c3cc8fae4efc81844e9b06f0eadf1b", "fullName": "test_dependency_8_4#test_a", "labels": [{"name": "tag", "value": "@pytest.mark.xfail(reason='deliberate fail')"}, {"name": "tag", "value": "dependency"}, {"name": "suite", "value": "test_dependency_8_4"}, {"name": "host", "value": "warronMacBook-Pro.local"}, {"name": "thread", "value": "55656-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_dependency_8_4"}]}