{"name": "test_assume", "status": "failed", "statusDetails": {"message": "pytest_assume.plugin.FailedAssumption: \n2 Failed Assumptions:\n\ntest_assume.py:20: AssumptionFailure\n>>\tpytest.assume(1 == 2)\nAssertionError: assert False\n\ntest_assume.py:21: AssumptionFailure\n>>\tpytest.assume(2 == 3)\nAssertionError: assert False", "trace": "tp = <class 'pytest_assume.plugin.FailedAssumption'>, value = None, tb = None\n\n    def reraise(tp, value, tb=None):\n        try:\n            if value is None:\n                value = tp()\n            if value.__traceback__ is not tb:\n>               raise value.with_traceback(tb)\nE               pytest_assume.plugin.FailedAssumption: \nE               2 Failed Assumptions:\nE               \nE               test_assume.py:20: AssumptionFailure\nE               >>\tpytest.assume(1 == 2)\nE               AssertionError: assert False\nE               \nE               test_assume.py:21: AssumptionFailure\nE               >>\tpytest.assume(2 == 3)\nE               AssertionError: assert False\n\n../../xunivenvs/hogwarts/lib/python3.6/site-packages/six.py:702: FailedAssumption"}, "start": 1622455414279, "stop": 1622455414276, "uuid": "913c586b-3a75-47a7-93c1-b624041c1a8c", "historyId": "c0c0e00a2dc8eb0c23efb3aaafbb3473", "testCaseId": "1fc213c51f170fbf8bc4aaf6544f8118", "fullName": "test_assume#test_assume", "labels": [{"name": "suite", "value": "test_assume"}, {"name": "host", "value": "warronMacBook-Pro.local"}, {"name": "thread", "value": "47370-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_assume"}]}